#!/usr/bin/env php
<?php

// Autoload composer components.
require __DIR__ . '/autoload.php';

use derhasi\drupalOrgIssuePatchHistory\Command;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Command\BuildBranchCommand());
$application->run();
