#!/usr/bin/env php
<?php

// Autoload composer components.
require __DIR__ . '/autoload.php';

//error_reporting(E_ALL);
//ini_set("display_errors", 1);

use derhasi\drupalOrgIssuePatchHistory\Command;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Command\BuildBranchCommand());
$application->run();
